// app/call-for-papers/page.tsx
import Navigation from '../components/Navigation'
import Footer from '../components/Footer'
import { Italic } from 'lucide-react'

// Helper function for GitHub Pages asset paths
const getAssetPath = (path: string) => {
  // For custom domain (www.aiagents4qual.org), use root paths
  // For GitHub Pages project mode, use repo base path
  const isCustomDomain = typeof window !== 'undefined' ? 
    window.location.hostname === 'www.aiagents4qual.org' || window.location.hostname === 'aiagents4qual.org' :
    process.env.NODE_ENV === 'production' && process.env.GITHUB_REPOSITORY === 'profmanagement/AIAgents4Qual';
  
  const basePath = (process.env.NODE_ENV === 'production' && !isCustomDomain) ? '/AIAgents4Qual' : '';
  return `${basePath}${path}`;
};

export default function CallForPapersPage() {
  return (
    <div className="min-h-screen bg-white">
      <Navigation />

      {/* Hero Section */}
      <section 
        className="section-padding relative overflow-hidden"
        style={{
          backgroundImage: `url(${getAssetPath("/images/hero-background-bubbles.svg")})`,
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat'
        }}
      >
        <div className="container text-center">
          <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-6">
            Call for Papers
          </h1>
          <p className="text-xl text-gray-700 max-w-3xl mx-auto">
            Submit your AI-generated research to the Open Conference of AI Agents for Qualitative Research (AI Agents4Qual) 2026!
          </p>
        </div>
      </section>

      {/* Submission Guidelines */}
      <section className="section-padding bg-white">
        <div className="container">
          <div className="max-w-4xl mx-auto space-y-8">

            {/* Conference Scope Section */}
            <div>
              <h2 className="text-3xl font-bold text-gray-900 mb-6">Conference Scope</h2>
              <p className="text-gray-700 leading-relaxed mb-4">
                <em>AI Writes, Humans Reflect</em>. The AI Agents4Qual 2026 is the first open conference where AI serves as both primary authors and reviewers of research papers in the field of qualitative research. It is also an experiment: What happens when we give generative AI the lead role in qualitative research and let humans step back — not to produce the content, but to reflect on the process and its effects? The aim is to explore future questions of AI-driven qualitative research discovery through a reflection on the AI-authored research and AI-master peer review process.
              </p>
              <p className="text-gray-700 leading-relaxed mb-4">
                <em>Experimentation at the Forefront</em>. This conference is not a conventional conference on AI in qualitative research. We do not want yet another set of papers on how ChatGPT or equivalent can help with coding, or how AI Assist supports MAXQDA, or AI coding support descriptive categorisations of qualitative material. There will be plenty of other venues for that, but not at this conference.
              </p>
              <p className="text-gray-700 leading-relaxed mb-4">
                <em>The Challenge</em>. We invite AI-generated qualitative research submissions where at least 50% of the output was generated by large language models (LLMs). The human contribution in content should be as minimal as possible, and each paper should include as  an essential part a reflection of the creation of the paper. So, every submission must include an autoethnographic account, addressing not only <em>how</em> you prompted any task in the LLM , but also <em>what</em> this process did to you as a researcher. How did it feel to hand over agency to the LLM and to share autonomy in the research process? Where did you resist, intervene, or let go? What surprised you? What unsettled you?
              </p>
              <p className="text-gray-700 leading-relaxed mb-4">
                <em>Focus Reflection</em>. This is not just about producing “good results.” It is about creativity, boundary-testing, and rethinking authorship, agency, and knowledge production in qualitative inquiry. Failures, glitches, and contradictions are not only acceptable — they are encouraged, if they include the abovementioned autoethnographic reflection. We want to explore the potentials and pitfalls of AI-driven qualitative research together.
              </p>
            </div>

            <div>
              <h2 className="text-3xl font-bold text-gray-900 mb-6">Participation</h2>
            </div>

            <p className="text-gray-700 leading-relaxed mb-4">
                The summit will take place exclusively online. Accepted papers will be orally presented at the conference and included in experimental proceedings. The event will culminate in a collective reflection: <em>What have we learned when AI took the helm of qualitative research?</em>
            </p>
                
            <p className="text-gray-700 leading-relaxed mb-4">   
                Details about how to register for the summit will be published soon.
            </p>
            
            <p className="text-gray-700 leading-relaxed mb-4"> 
            <strong>Come and Join the Experiment!</strong>
            </p>

            <p className="text-gray-700 leading-relaxed mb-4"> 
            <strong>AI Agents4Qual 2026</strong> is not about incremental improvements. It is about turning things upside down. Let AI write, let humans reflect — and let us see what happens when qualitative research is radically reimagined.
            </p>

            <div>
              <h2 className="text-3xl font-bold text-gray-900 mb-6">Submission Requirements</h2>
            </div>

            {/* Main Paper Section */}
            <div className="card">
              <h3 className="text-2xl font-bold text-gray-900 mb-6">Main Paper</h3>

              <div className="space-y-4 mb-6">
                <ul className="space-y-2 text-gray-700">
                  <li>• <strong>Papers must be predominantly authored by generative AI systems</strong> (ChatGPT, Claude, LLaMA, etc.).</li>
                  <li>• <strong>Authors must disclose and reflect</strong> on the distribution of roles between AI and human.</li>
                  <li>• <strong>Each submission must include an autoethnographic reflection:</strong> What happened when you gave AI the lead, and how did it affect you as a scholar?</li>
                  <li>• <strong>Submissions that reduce AI to a mere assistant or tool</strong> (e.g. coding support, summarization) will not be considered.</li>
                  <li>• <strong>Page Limit:</strong> Submissions must be no more than 8 pages, excluding references and required statements.</li>
                  <li>• <strong>Template Requirement:</strong> All papers must use the official conference template (Link to page), which includes a mandatory AI Contribution Disclosure checklist.</li>
                  <li>• <strong>Submission Platform:</strong> Submissions must be made via <a href="https://openreview.net" className="text-blue-600 underline hover:text-blue-800">OpenReview</a>.</li>
                  <li>• <strong>Anonymity:</strong> Submissions must be anonymous and should not include author names, affiliations, or other identifying information in the main text.</li>
                </ul>
              </div>

              {/* Template Download Section */}
              <div className="bg-gray-50 rounded-lg p-6 border border-gray-200">
                <div className="text-center">
                  <h4 className="text-lg font-semibold text-blue-600 mb-2 flex items-center justify-center">
                    <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    Download Template
                  </h4>
                  <p className="text-gray-700 mb-4">
                    Download the official Word template with AI Contribution Disclosure checklist
                  </p>
                  <a 
                    href={getAssetPath("/templates/Template_Paper Submission_AI Agents4QualResearch_2025.docx")}
                    download="Template_Paper Submission_AI Agents4QualResearch_2025.docx"
                    className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-6 rounded-md transition-colors flex items-center mx-auto inline-flex"
                  >
                    <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    Download Word Template
                  </a>
                  <div className="mt-4 flex items-center justify-center text-red-600 text-sm">
                    <svg className="w-3 h-3 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L3.732 16.5c-.77.833.192 2.5 1.732 2.5z" />
                    </svg>
                    Please make sure to carefully complete the required checklist and the statements (see below)
                  </div>
                </div>
              </div>
            </div>

            {/* Three Statement Cards */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {/* AI Research Autonomy Disclosure */}
              <div className="card text-center">
                <div className="w-12 h-12 bg-blue-600 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                  </svg>
                </div>
                <h4 className="text-lg font-semibold text-gray-900 mb-3">AI Research Autonomy Disclosure</h4>
                <p className="text-gray-700 text-sm">
                  We will provide an AI usage checklist that authors must complete for each submission. This checklist will document the roles of both AI and human contributors across various aspects of the research project, including hypothesis generation, method development, data handling and analysis, results interpretation, writing, and visualization.
                </p>
              </div>

              {/* Responsible AI Statement */}
              <div className="card text-center">
                <div className="w-12 h-12 bg-blue-600 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
                  </svg>
                </div>
                <h4 className="text-lg font-semibold text-gray-900 mb-3">Responsible AI Statement</h4>
                <p className="text-gray-700 text-sm">
                  Each submission must adhere to the <a href="https://www.apa.org/ethics/code" className="text-blue-600 underline hover:text-blue-800">APA Code of Ethics</a> and include a statement discussing the broader impact of the research, as well as any precautions taken to ensure the safe deployment of the AI scientist. This statement will not count toward the page limit.
                </p>
              </div>

              {/* Reproducibility Statement */}
              <div className="card text-center">
                <div className="w-12 h-12 bg-blue-600 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                  </svg>
                </div>
                <h4 className="text-lg font-semibold text-gray-900 mb-3">Reproducibility Statement</h4>
                <p className="text-gray-700 text-sm">
                  Authors are strongly encouraged to include a paragraph-long Reproducibility Statement at the end of the main text to discuss the efforts that have been made to ensure reproducibility. This does not count toward the page limit.
                </p>
              </div>
            </div>

            {/* Review Process Section */}
            <div>
              <h3 className="text-2xl font-bold text-gray-900 mb-6 text-center">Review Process</h3>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Card 1: Multi-AI Review Panel */}
                <div className="card text-center">
                  <div className="w-12 h-12 bg-blue-600 rounded-full flex items-center justify-center mx-auto mb-4">
                    <span className="text-white font-bold text-lg">1</span>
                  </div>
                  <h4 className="text-lg font-semibold text-gray-900 mb-3">Multi-AI Review Panel</h4>
                  <p className="text-gray-700">
                    Each paper will be evaluated by multiple AI systems to avoid biases from one particular model, guided by a shared framework.
                  </p>
                </div>

                {/* Card 2: Human Oversight Committee */}
                <div className="card text-center">
                  <div className="w-12 h-12 bg-blue-600 rounded-full flex items-center justify-center mx-auto mb-4">
                    <span className="text-white font-bold text-lg">2</span>
                  </div>
                  <h4 className="text-lg font-semibold text-gray-900 mb-3">Minimal Human Oversight</h4>
                  <p className="text-gray-700">
                    Human organizers will only look at the top-ranked submissions and may select from them for presentation. 
                  </p>
                </div>
                
              </div>
            </div>

            {/* Review Template & Scoring Section */}
            <div className="card">
              <h3 className="text-2xl font-bold text-gray-900 mb-6">Review Template & Scoring</h3>

              <div className="space-y-4">
                <p className="text-gray-700">
                  Reviews will be carried out by three large language models, guided by a shared framework. So, each paper will be evaluated by multiple AI systems to avoid biases from one particular model. Human organizers will only look at the top-ranked submissions and may select from them for presentation. The review process itself is part of the experiment: after the conference, the community will reflect on the quality of AI reviews compared to human judgment. Each paper will be evaluated by multiple AI systems to avoid biases from one particular model.
                </p>

                <p className="text-gray-700">
                  Every paper will also be scored on according to the <strong><a href={getAssetPath("/templates/AI Reviewer Checklist AIAgent4QualResearch.pdf")} className="text-blue-600 hover:text-blue-800 underline" target="_blank" rel="noopener noreferrer">CASP instructions and rubric</a></strong>.
                </p>

              </div>
            </div>

            <div className="card">
              <h3 className="text-xl font-semibold text-gray-900 mb-3">AI Model Requirements</h3>
              <p className="text-gray-700">
                You may use any open-source or proprietary models, multiple agents, tools (e.g., ChatGPT, Claude, Gemini), or build your own research agent. The key requirement is that the research must be primarily conducted and written by AI agents.
              </p>
            </div>

            <div className="card">
              <h3 className="text-xl font-semibold text-gray-900 mb-3">Contact</h3>
              <p className="text-gray-700">
                For questions about submissions or the conference, please contact us at{' '}
                <a href="mailto:ai.agents4qual@gmail.com" className="text-blue-600 hover:text-blue-800">
                  ai.agents4qual@gmail.com
                </a>
              </p>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  )
}
